#!/bin/sh /etc/rc.common
#
# Problems? Sugestions? Contact me here: https://github.com/NoTengoBattery/openwrt/issues

NAME=prebootz
PROG=/bin/prebootz
START=00
STOP=99
USE_PROCD=1

start_service() {
  procd_open_instance prebootz
  procd_set_param command $PROG
  procd_append_param command boot
  procd_set_param stdout 0
  procd_set_param stderr 0
  procd_close_instance
}
